# Generated by Django 4.2.4 on 2023-08-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0002_delete_event_details_delete_event_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="event_template",
            fields=[
                ("template_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("birthday", "birthday"),
                            ("work anniversery", "work anniversery"),
                        ],
                        default="birthday",
                        max_length=30,
                    ),
                ),
                ("template", models.TextField()),
            ],
        ),
    ]
